### ISSUE TITLE
Mejoras sugeridas para el proyecto

### ISSUE THREAD

**Issue by joserafael0160** [cfurrutia/Viajes-Chile#1]
Hola, me gustaría sugerir algunas mejoras para tu proyecto:

1. **Enlace al proyecto desplegado:** He notado que el proyecto está desplegado, pero no hay un enlace en el repositorio de GitHub para acceder a él. Sería útil añadir este enlace en la descripción del repositorio o en el archivo README para que los visitantes puedan ver fácilmente la versión en vivo del proyecto.

2. **Archivo README:** Actualmente, el proyecto no tiene un archivo README que describa adecuadamente el proyecto, su propósito, qué tecnologías  usaste, cómo contribuir en él y cómo usarlo. Un buen archivo README puede ser muy útil para los visitantes que quieran entender mejor el proyecto, contribuir a él o usarlo.

3. **Esquema de color:** El color azul celeste utilizado en el proyecto es bastante claro, lo que hace que el texto blanco sea difícil de leer. Consideraría utilizar un tono de azul más oscuro para mejorar la legibilidad y la experiencia del usuario.

Espero que estas sugerencias sean útiles. ¡Gracias por tu gran trabajo en este proyecto!

**Comment by cfurrutia** [comment]
Te agradezco por tomarte el tiempo de darme estos consejos.
